import {RGB} from "./RGB"
export const pcolors = {
"Absolute Zero 	": new RGB("#0048BA"),
"Acid green 	": new RGB("#B0BF1A"),
"Aero 	": new RGB("#7CB9E8"),
"Aero blue 	": new RGB("#C0E8D5"),
"African violet 	": new RGB("#B284BE"),
"Air superiority blue 	": new RGB("#72A0C1"),
"Alabaster 	": new RGB("#EDEAE0"),
"Alice blue 	": new RGB("#F0F8FF"),
"Alloy orange 	": new RGB("#C46210"),
"Almond 	": new RGB("#EFDECD"),
"Amaranth 	": new RGB("#E52B50"),
"Amaranth (M&P) 	": new RGB("#9F2B68"),
"Amaranth pink 	": new RGB("#F19CBB"),
"Amaranth purple 	": new RGB("#AB274F"),
"Amaranth red 	": new RGB("#D3212D"),
"Amazon 	": new RGB("#3B7A57"),
"Amber 	": new RGB("#FFBF00"),
"Amber (SAE/ECE) 	": new RGB("#FF7E00"),
"Amethyst 	": new RGB("#9966CC"),
"Android green 	": new RGB("#A4C639"),
"Antique brass 	": new RGB("#CD9575"),
"Antique bronze 	": new RGB("#665D1E"),
"Antique fuchsia 	": new RGB("#915C83"),
"Antique ruby 	": new RGB("#841B2D"),
"Antique white 	": new RGB("#FAEBD7"),
"Ao (English) 	": new RGB("#008000"),
"Apple green 	": new RGB("#8DB600"),
"Apricot 	": new RGB("#FBCEB1"),
"Aqua 	": new RGB("#00FFFF"),
"Aquamarine 	": new RGB("#7FFFD4"),
"Arctic lime 	": new RGB("#D0FF14"),
"Army green 	": new RGB("#4B5320"),
"Artichoke 	": new RGB("#8F9779"),
"Arylide yellow 	": new RGB("#E9D66B"),
"Ash gray 	": new RGB("#B2BEB5"),
"Asparagus 	": new RGB("#87A96B"),
"Atomic tangerine 	": new RGB("#FF9966"),
"Auburn 	": new RGB("#A52A2A"),
"Aureolin 	": new RGB("#FDEE00"),
"Avocado 	": new RGB("#568203"),
"Azure 	": new RGB("#007FFF"),
"Azure (X11/web color) 	": new RGB("#F0FFFF"),
"B'dazzled blue 	": new RGB("#2E5894"),
"Baby blue 	": new RGB("#89CFF0"),
"Baby blue eyes 	": new RGB("#A1CAF1"),
"Baby pink 	": new RGB("#F4C2C2"),
"Baby powder 	": new RGB("#FEFEFA"),
"Baker-Miller pink 	": new RGB("#FF91AF"),
"Banana Mania 	": new RGB("#FAE7B5"),
"Barbie Pink 	": new RGB("#DA1884"),
"Barn red 	": new RGB("#7C0A02"),
"Battleship grey 	": new RGB("#848482"),
"Beau blue 	": new RGB("#BCD4E6"),
"Beaver 	": new RGB("#9F8170"),
"Beige 	": new RGB("#F5F5DC"),
"Big dip o’ruby 	": new RGB("#9C2542"),
"Bisque 	": new RGB("#FFE4C4"),
"Bistre 	": new RGB("#3D2B1F"),
"Bistre brown 	": new RGB("#967117"),
"Bitter lemon 	": new RGB("#CAE00D"),
"Bitter lime 	": new RGB("#BFFF00"),
"Bittersweet 	": new RGB("#FE6F5E"),
"Bittersweet shimmer 	": new RGB("#BF4F51"),
"Black 	": new RGB("#000000"),
"Black bean 	": new RGB("#3D0C02"),
"Black chocolate 	": new RGB("#1B1811"),
"Black coffee 	": new RGB("#3B2F2F"),
"Black coral 	": new RGB("#54626F"),
"Black olive 	": new RGB("#3B3C36"),
"Black Shadows 	": new RGB("#BFAFB2"),
"Blanched almond 	": new RGB("#FFEBCD"),
"Blast-off bronze 	": new RGB("#A57164"),
"Bleu de France 	": new RGB("#318CE7"),
"Blizzard blue 	": new RGB("#ACE5EE"),
"Blond 	": new RGB("#FAF0BE"),
"Blood red 	": new RGB("#660000"),
"Blue 	": new RGB("#0000FF"),
"Blue (Crayola) 	": new RGB("#1F75FE"),
"Blue (Munsell) 	": new RGB("#0093AF"),
"Blue (NCS) 	": new RGB("#0087BD"),
"Blue (Pantone) 	": new RGB("#0018A8"),
"Blue (pigment) 	": new RGB("#333399"),
"Blue (RYB) 	": new RGB("#0247FE"),
"Blue bell 	": new RGB("#A2A2D0"),
"Blue jeans 	": new RGB("#5DADEC"),
"Blue sapphire 	": new RGB("#126180"),
"Blue yonder 	": new RGB("#5072A7"),
"Blue-gray 	": new RGB("#6699CC"),
"Blue-green 	": new RGB("#0D98BA"),
"Blue-green (color wheel) 	": new RGB("#064E40"),
"Blue-violet 	": new RGB("#8A2BE2"),
"Blue-violet (color wheel) 	": new RGB("#4D1A7F"),
"Blue-violet (Crayola) 	": new RGB("#7366BD"),
"Bluetiful 	": new RGB("#3C69E7"),
"Blush 	": new RGB("#DE5D83"),
"Bole 	": new RGB("#79443B"),
"Bone 	": new RGB("#E3DAC9"),
"Bottle green 	": new RGB("#006A4E"),
"Brandy 	": new RGB("#87413F"),
"Brick red 	": new RGB("#CB4154"),
"Bright green 	": new RGB("#66FF00"),
"Bright lilac 	": new RGB("#D891EF"),
"Bright maroon 	": new RGB("#C32148"),
"Bright navy blue 	": new RGB("#1974D2"),
"Bright yellow (Crayola) 	": new RGB("#FFAA1D"),
"Brilliant rose 	": new RGB("#FF55A3"),
"Brink pink 	": new RGB("#FB607F"),
"British racing green 	": new RGB("#004225"),
"Bronze 	": new RGB("#CD7F32"),
"Brown 	": new RGB("#88540B"),
"Brown sugar 	": new RGB("#AF6E4D"),
"Brunswick green 	": new RGB("#1B4D3E"),
"Bud green 	": new RGB("#7BB661"),
"Buff 	": new RGB("#FFC680"),
"Burgundy 	": new RGB("#800020"),
"Burlywood 	": new RGB("#DEB887"),
"Burnished brown 	": new RGB("#A17A74"),
"Burnt orange 	": new RGB("#CC5500"),
"Burnt sienna 	": new RGB("#E97451"),
"Burnt umber 	": new RGB("#8A3324"),
"Byzantine 	": new RGB("#BD33A4"),
"Byzantium 	": new RGB("#702963"),
"Cadet 	": new RGB("#536872"),
"Cadet blue 	": new RGB("#5F9EA0"),
"Cadet blue (Crayola) 	": new RGB("#A9B2C3"),
"Cadet grey 	": new RGB("#91A3B0"),
"Cadmium green 	": new RGB("#006B3C"),
"Cadmium orange 	": new RGB("#ED872D"),
"Cadmium red 	": new RGB("#E30022"),
"Cadmium yellow 	": new RGB("#FFF600"),
"Café au lait 	": new RGB("#A67B5B"),
"Café noir 	": new RGB("#4B3621"),
"Cambridge blue 	": new RGB("#A3C1AD"),
"Camel 	": new RGB("#C19A6B"),
"Cameo pink 	": new RGB("#EFBBCC"),
"Canary 	": new RGB("#FFFF99"),
"Canary yellow 	": new RGB("#FFEF00"),
"Candy apple red 	": new RGB("#FF0800"),
"Candy pink 	": new RGB("#E4717A"),
"Capri 	": new RGB("#00BFFF"),
"Caput mortuum 	": new RGB("#592720"),
"Cardinal 	": new RGB("#C41E3A"),
"Caribbean green 	": new RGB("#00CC99"),
"Carmine 	": new RGB("#960018"),
"Carmine (M&P) 	": new RGB("#D70040"),
"Carnation pink 	": new RGB("#FFA6C9"),
"Carnelian 	": new RGB("#B31B1B"),
"Carolina blue 	": new RGB("#56A0D3"),
"Carrot orange 	": new RGB("#ED9121"),
"Castleton green 	": new RGB("#00563F"),
"Catawba 	": new RGB("#703642"),
"Cedar Chest 	": new RGB("#C95A49"),
"Celadon 	": new RGB("#ACE1AF"),
"Celadon blue 	": new RGB("#007BA7"),
"Celadon green 	": new RGB("#2F847C"),
"Celeste 	": new RGB("#B2FFFF"),
"Celtic blue 	": new RGB("#246BCE"),
"Cerise 	": new RGB("#DE3163"),
"Cerulean 	": new RGB("#007BA7"),
"Cerulean (Crayola) 	": new RGB("#1DACD6"),
"Cerulean blue 	": new RGB("#2A52BE"),
"Cerulean frost 	": new RGB("#6D9BC3"),
"CG blue 	": new RGB("#007AA5"),
"CG red 	": new RGB("#E03C31"),
"Champagne 	": new RGB("#F7E7CE"),
"Champagne pink 	": new RGB("#F1DDCF"),
"Charcoal 	": new RGB("#36454F"),
"Charleston green 	": new RGB("#232B2B"),
"Charm pink 	": new RGB("#E68FAC"),
"Chartreuse (traditional) 	": new RGB("#DFFF00"),
"Chartreuse (web) 	": new RGB("#7FFF00"),
"Cherry blossom pink 	": new RGB("#FFB7C5"),
"Chestnut 	": new RGB("#954535"),
"Chili red 	": new RGB("#E23D28"),
"China pink 	": new RGB("#DE6FA1"),
"China rose 	": new RGB("#A8516E"),
"Chinese red 	": new RGB("#AA381E"),
"Chinese violet 	": new RGB("#856088"),
"Chinese yellow 	": new RGB("#FFB200"),
"Chocolate (traditional) 	": new RGB("#7B3F00"),
"Chocolate (web) 	": new RGB("#D2691E"),
"Chocolate Cosmos 	": new RGB("#58111A"),
"Chrome yellow 	": new RGB("#FFA700"),
"Cinereous 	": new RGB("#98817B"),
"Cinnabar 	": new RGB("#E34234"),
"Cinnamon Satin 	": new RGB("#CD607E"),
"Citrine 	": new RGB("#E4D00A"),
"Citron 	": new RGB("#9FA91F"),
"Claret 	": new RGB("#7F1734"),
"Cobalt blue 	": new RGB("#0047AB"),
"Cocoa brown 	": new RGB("#D2691E"),
"Coffee 	": new RGB("#6F4E37"),
"Columbia Blue 	": new RGB("#B9D9EB"),
"Congo pink 	": new RGB("#F88379"),
"Cool grey 	": new RGB("#8C92AC"),
"Copper 	": new RGB("#B87333"),
"Copper (Crayola) 	": new RGB("#DA8A67"),
"Copper penny 	": new RGB("#AD6F69"),
"Copper red 	": new RGB("#CB6D51"),
"Copper rose 	": new RGB("#996666"),
"Coquelicot 	": new RGB("#FF3800"),
"Coral 	": new RGB("#FF7F50"),
"Coral pink 	": new RGB("#F88379"),
"Cordovan 	": new RGB("#893F45"),
"Corn 	": new RGB("#FBEC5D"),
"Cornell red 	": new RGB("#B31B1B"),
"Cornflower blue 	": new RGB("#6495ED"),
"Cornsilk 	": new RGB("#FFF8DC"),
"Cosmic cobalt 	": new RGB("#2E2D88"),
"Cosmic latte 	": new RGB("#FFF8E7"),
"Cotton candy 	": new RGB("#FFBCD9"),
"Coyote brown 	": new RGB("#81613C"),
"Cream 	": new RGB("#FFFDD0"),
"Crimson 	": new RGB("#DC143C"),
"Crimson (UA) 	": new RGB("#9E1B32"),
"Crystal 	": new RGB("#A7D8DE"),
"Cultured 	": new RGB("#F5F5F5"),
"Cyan 	": new RGB("#00FFFF"),
"Cyan (process) 	": new RGB("#00B7EB"),
"Cyber grape 	": new RGB("#58427C"),
"Cyber yellow 	": new RGB("#FFD300"),
"Cyclamen 	": new RGB("#F56FA1"),
"Dark blue-gray 	": new RGB("#666699"),
"Dark brown 	": new RGB("#654321"),
"Dark byzantium 	": new RGB("#5D3954"),
"Dark cornflower blue 	": new RGB("#26428B"),
"Dark cyan 	": new RGB("#008B8B"),
"Dark electric blue 	": new RGB("#536878"),
"Dark goldenrod 	": new RGB("#B8860B"),
"Dark green 	": new RGB("#013220"),
"Dark green (X11) 	": new RGB("#006400"),
"Dark jungle green 	": new RGB("#1A2421"),
"Dark khaki 	": new RGB("#BDB76B"),
"Dark lava 	": new RGB("#483C32"),
"Dark liver 	": new RGB("#534B4F"),
"Dark liver (horses) 	": new RGB("#543D37"),
"Dark magenta 	": new RGB("#8B008B"),
"Dark moss green 	": new RGB("#4A5D23"),
"Dark olive green 	": new RGB("#556B2F"),
"Dark orange 	": new RGB("#FF8C00"),
"Dark orchid 	": new RGB("#9932CC"),
"Dark pastel green 	": new RGB("#03C03C"),
"Dark purple 	": new RGB("#301934"),
"Dark red 	": new RGB("#8B0000"),
"Dark salmon 	": new RGB("#E9967A"),
"Dark sea green 	": new RGB("#8FBC8F"),
"Dark sienna 	": new RGB("#3C1414"),
"Dark sky blue 	": new RGB("#8CBED6"),
"Dark slate blue 	": new RGB("#483D8B"),
"Dark slate gray 	": new RGB("#2F4F4F"),
"Dark spring green 	": new RGB("#177245"),
"Dark turquoise 	": new RGB("#00CED1"),
"Dark violet 	": new RGB("#9400D3"),
"Dartmouth green 	": new RGB("#00703C"),
"Davy's grey 	": new RGB("#555555"),
"Deep cerise 	": new RGB("#DA3287"),
"Deep champagne 	": new RGB("#FAD6A5"),
"Deep chestnut 	": new RGB("#B94E48"),
"Deep jungle green 	": new RGB("#004B49"),
"Deep pink 	": new RGB("#FF1493"),
"Deep saffron 	": new RGB("#FF9933"),
"Deep sky blue 	": new RGB("#00BFFF"),
"Deep Space Sparkle 	": new RGB("#4A646C"),
"Deep taupe 	": new RGB("#7E5E60"),
"Denim 	": new RGB("#1560BD"),
"Denim blue 	": new RGB("#2243B6"),
"Desert 	": new RGB("#C19A6B"),
"Desert sand 	": new RGB("#EDC9AF"),
"Dim gray 	": new RGB("#696969"),
"Dodger blue 	": new RGB("#1E90FF"),
"Dogwood rose 	": new RGB("#D71868"),
"Drab 	": new RGB("#967117"),
"Duke blue 	": new RGB("#00009C"),
"Dutch white 	": new RGB("#EFDFBB"),
"Earth yellow 	": new RGB("#E1A95F"),
"Ebony 	": new RGB("#555D50"),
"Ecru 	": new RGB("#C2B280"),
"Eerie black 	": new RGB("#1B1B1B"),
"Eggplant 	": new RGB("#614051"),
"Eggshell 	": new RGB("#F0EAD6"),
"Egyptian blue 	": new RGB("#1034A6"),
"Eigengrau 	": new RGB("#16161D"),
"Electric blue 	": new RGB("#7DF9FF"),
"Electric green 	": new RGB("#00FF00"),
"Electric indigo 	": new RGB("#6F00FF"),
"Electric lime 	": new RGB("#CCFF00"),
"Electric purple 	": new RGB("#BF00FF"),
"Electric violet 	": new RGB("#8F00FF"),
"Emerald 	": new RGB("#50C878"),
"Eminence 	": new RGB("#6C3082"),
"English green 	": new RGB("#1B4D3E"),
"English lavender 	": new RGB("#B48395"),
"English red 	": new RGB("#AB4B52"),
"English vermillion 	": new RGB("#CC474B"),
"English violet 	": new RGB("#563C5C"),
"Erin 	": new RGB("#00FF40"),
"Eton blue 	": new RGB("#96C8A2"),
"Fallow 	": new RGB("#C19A6B"),
"Falu red 	": new RGB("#801818"),
"Fandango 	": new RGB("#B53389"),
"Fandango pink 	": new RGB("#DE5285"),
"Fashion fuchsia 	": new RGB("#F400A1"),
"Fawn 	": new RGB("#E5AA70"),
"Feldgrau 	": new RGB("#4D5D53"),
"Fern green 	": new RGB("#4F7942"),
"Field drab 	": new RGB("#6C541E"),
"Fiery rose 	": new RGB("#FF5470"),
"Fire engine red 	": new RGB("#CE2029"),
"Fire opal 	": new RGB("#E95C4B"),
"Firebrick 	": new RGB("#B22222"),
"Flame 	": new RGB("#E25822"),
"Flax 	": new RGB("#EEDC82"),
"Flirt 	": new RGB("#A2006D"),
"Floral white 	": new RGB("#FFFAF0"),
"Fluorescent blue 	": new RGB("#15F4EE"),
"Forest green (Crayola) 	": new RGB("#5FA777"),
"Forest green (traditional) 	": new RGB("#014421"),
"Forest green (web) 	": new RGB("#228B22"),
"French beige 	": new RGB("#A67B5B"),
"French bistre 	": new RGB("#856D4D"),
"French blue 	": new RGB("#0072BB"),
"French fuchsia 	": new RGB("#FD3F92"),
"French lilac 	": new RGB("#86608E"),
"French lime 	": new RGB("#9EFD38"),
"French mauve 	": new RGB("#D473D4"),
"French pink 	": new RGB("#FD6C9E"),
"French raspberry 	": new RGB("#C72C48"),
"French rose 	": new RGB("#F64A8A"),
"French sky blue 	": new RGB("#77B5FE"),
"French violet 	": new RGB("#8806CE"),
"Frostbite 	": new RGB("#E936A7"),
"Fuchsia 	": new RGB("#FF00FF"),
"Fuchsia (Crayola) 	": new RGB("#C154C1"),
"Fuchsia purple 	": new RGB("#CC397B"),
"Fuchsia rose 	": new RGB("#C74375"),
"Fulvous 	": new RGB("#E48400"),
"Fuzzy Wuzzy 	": new RGB("#87421F"),
"Gainsboro 	": new RGB("#DCDCDC"),
"Gamboge 	": new RGB("#E49B0F"),
"Generic viridian 	": new RGB("#007F66"),
"Ghost white 	": new RGB("#F8F8FF"),
"Glaucous 	": new RGB("#6082B6"),
"Glossy grape 	": new RGB("#AB92B3"),
"GO green 	": new RGB("#00AB66"),
"Gold 	": new RGB("#A57C00"),
"Gold (metallic) 	": new RGB("#D4AF37"),
"Gold (web) (Golden) 	": new RGB("#FFD700"),
"Gold (Crayola) 	": new RGB("#E6BE8A"),
"Gold Fusion 	": new RGB("#85754E"),
"Golden brown 	": new RGB("#996515"),
"Golden poppy 	": new RGB("#FCC200"),
"Golden yellow 	": new RGB("#FFDF00"),
"Goldenrod 	": new RGB("#DAA520"),
"Granite gray 	": new RGB("#676767"),
"Granny Smith apple 	": new RGB("#A8E4A0"),
"Gray (web) 	": new RGB("#808080"),
"Gray (X11 gray) 	": new RGB("#BEBEBE"),
"Green 	": new RGB("#00FF00"),
"Green (Crayola) 	": new RGB("#1CAC78"),
"Green (web) 	": new RGB("#008000"),
"Green (Munsell) 	": new RGB("#00A877"),
"Green (NCS) 	": new RGB("#009F6B"),
"Green (Pantone) 	": new RGB("#00AD43"),
"Green (pigment) 	": new RGB("#00A550"),
"Green (RYB) 	": new RGB("#66B032"),
"Green-blue 	": new RGB("#1164B4"),
"Green-blue (Crayola) 	": new RGB("#2887C8"),
"Green-cyan 	": new RGB("#009966"),
"Green Lizard 	": new RGB("#A7F432"),
"Green Sheen 	": new RGB("#6EAEA1"),
"Green-yellow 	": new RGB("#ADFF2F"),
"Green-yellow (Crayola) 	": new RGB("#F0E891"),
"Grullo 	": new RGB("#A99A86"),
"Gunmetal 	": new RGB("#2a3439"),
"Han blue 	": new RGB("#446CCF"),
"Han purple 	": new RGB("#5218FA"),
"Hansa yellow 	": new RGB("#E9D66B"),
"Harlequin 	": new RGB("#3FFF00"),
"Harvest gold 	": new RGB("#DA9100"),
"Heat Wave 	": new RGB("#FF7A00"),
"Heliotrope 	": new RGB("#DF73FF"),
"Heliotrope gray 	": new RGB("#AA98A9"),
"Hollywood cerise 	": new RGB("#F400A1"),
"Honeydew 	": new RGB("#F0FFF0"),
"Honolulu blue 	": new RGB("#006DB0"),
"Hooker's green 	": new RGB("#49796B"),
"Hot magenta 	": new RGB("#FF1DCE"),
"Hot pink 	": new RGB("#FF69B4"),
"Hunter green 	": new RGB("#355E3B"),
"Iceberg 	": new RGB("#71A6D2"),
"Icterine 	": new RGB("#FCF75E"),
"Illuminating emerald 	": new RGB("#319177"),
"Imperial red 	": new RGB("#ED2939"),
"Inchworm 	": new RGB("#B2EC5D"),
"Independence 	": new RGB("#4C516D"),
"India green 	": new RGB("#138808"),
"Indian red 	": new RGB("#CD5C5C"),
"Indian yellow 	": new RGB("#E3A857"),
"Indigo 	": new RGB("#4B0082"),
"Indigo dye 	": new RGB("#00416A"),
"International orange (aerospace) 	": new RGB("#FF4F00"),
"International orange (engineering) 	": new RGB("#BA160C"),
"International orange (Golden Gate Bridge) 	": new RGB("#C0362C"),
"Iris 	": new RGB("#5A4FCF"),
"Irresistible 	": new RGB("#B3446C"),
"Isabelline 	": new RGB("#F4F0EC"),
"Italian sky blue 	": new RGB("#B2FFFF"),
"Ivory 	": new RGB("#FFFFF0"),
"Jade 	": new RGB("#00A86B"),
"Japanese carmine 	": new RGB("#9D2933"),
"Japanese violet 	": new RGB("#5B3256"),
"Jasmine 	": new RGB("#F8DE7E"),
"Jazzberry jam 	": new RGB("#A50B5E"),
"Jet 	": new RGB("#343434"),
"Jonquil 	": new RGB("#F4CA16"),
"June bud 	": new RGB("#BDDA57"),
"Jungle green 	": new RGB("#29AB87"),
"Kelly green 	": new RGB("#4CBB17"),
"Keppel 	": new RGB("#3AB09E"),
"Key lime 	": new RGB("#E8F48C"),
"Khaki (web) 	": new RGB("#C3B091"),
"Khaki (X11) (Light khaki) 	": new RGB("#F0E68C"),
"Kobe 	": new RGB("#882D17"),
"Kobi 	": new RGB("#E79FC4"),
"Kobicha 	": new RGB("#6B4423"),
"Kombu green 	": new RGB("#354230"),
"KSU purple 	": new RGB("#512888"),
"Languid lavender 	": new RGB("#D6CADD"),
"Lapis lazuli 	": new RGB("#26619C"),
"Laser lemon 	": new RGB("#FFFF66"),
"Laurel green 	": new RGB("#A9BA9D"),
"Lava 	": new RGB("#CF1020"),
"Lavender (floral) 	": new RGB("#B57EDC"),
"Lavender (web) 	": new RGB("#E6E6FA"),
"Lavender blue 	": new RGB("#CCCCFF"),
"Lavender blush 	": new RGB("#FFF0F5"),
"Lavender gray 	": new RGB("#C4C3D0"),
"Lawn green 	": new RGB("#7CFC00"),
"Lemon 	": new RGB("#FFF700"),
"Lemon chiffon 	": new RGB("#FFFACD"),
"Lemon curry 	": new RGB("#CCA01D"),
"Lemon glacier 	": new RGB("#FDFF00"),
"Lemon meringue 	": new RGB("#F6EABE"),
"Lemon yellow 	": new RGB("#FFF44F"),
"Lemon yellow (Crayola) 	": new RGB("#FFFF9F"),
"Liberty 	": new RGB("#545AA7"),
"Light blue 	": new RGB("#ADD8E6"),
"Light coral 	": new RGB("#F08080"),
"Light cornflower blue 	": new RGB("#93CCEA"),
"Light cyan 	": new RGB("#E0FFFF"),
"Light French beige 	": new RGB("#C8AD7F"),
"Light goldenrod yellow 	": new RGB("#FAFAD2"),
"Light gray 	": new RGB("#D3D3D3"),
"Light green 	": new RGB("#90EE90"),
"Light orange 	": new RGB("#FED8B1"),
"Light periwinkle 	": new RGB("#C5CBE1"),
"Light pink 	": new RGB("#FFB6C1"),
"Light salmon 	": new RGB("#FFA07A"),
"Light sea green 	": new RGB("#20B2AA"),
"Light sky blue 	": new RGB("#87CEFA"),
"Light slate gray 	": new RGB("#778899"),
"Light steel blue 	": new RGB("#B0C4DE"),
"Light yellow 	": new RGB("#FFFFE0"),
"Lilac 	": new RGB("#C8A2C8"),
"Lilac Luster 	": new RGB("#AE98AA"),
"Lime (color wheel) 	": new RGB("#BFFF00"),
"Lime (web) (X11 green) 	": new RGB("#00FF00"),
"Lime green 	": new RGB("#32CD32"),
"Lincoln green 	": new RGB("#195905"),
"Linen 	": new RGB("#FAF0E6"),
"Lion 	": new RGB("#C19A6B"),
"Liseran purple 	": new RGB("#DE6FA1"),
"Little boy blue 	": new RGB("#6CA0DC"),
"Liver 	": new RGB("#674C47"),
"Liver (dogs) 	": new RGB("#B86D29"),
"Liver (organ) 	": new RGB("#6C2E1F"),
"Liver chestnut 	": new RGB("#987456"),
"Livid 	": new RGB("#6699CC"),
"Macaroni and Cheese 	": new RGB("#FFBD88"),
"Madder Lake 	": new RGB("#CC3336"),
"Magenta 	": new RGB("#FF00FF"),
"Magenta (Crayola) 	": new RGB("#F653A6"),
"Magenta (dye) 	": new RGB("#CA1F7B"),
"Magenta (Pantone) 	": new RGB("#D0417E"),
"Magenta (process) 	": new RGB("#FF0090"),
"Magenta haze 	": new RGB("#9F4576"),
"Magic mint 	": new RGB("#AAF0D1"),
"Magnolia 	": new RGB("#F2E8D7"),
"Mahogany 	": new RGB("#C04000"),
"Maize 	": new RGB("#FBEC5D"),
"Maize (Crayola) 	": new RGB("#F2C649"),
"Majorelle blue 	": new RGB("#6050DC"),
"Malachite 	": new RGB("#0BDA51"),
"Manatee 	": new RGB("#979AAA"),
"Mandarin 	": new RGB("#F37A48"),
"Mango 	": new RGB("#FDBE02"),
"Mango Tango 	": new RGB("#FF8243"),
"Mantis 	": new RGB("#74C365"),
"Mardi Gras 	": new RGB("#880085"),
"Marigold 	": new RGB("#EAA221"),
"Maroon (Crayola) 	": new RGB("#C32148"),
"Maroon (web) 	": new RGB("#800000"),
"Maroon (X11) 	": new RGB("#B03060"),
"Mauve 	": new RGB("#E0B0FF"),
"Mauve taupe 	": new RGB("#915F6D"),
"Mauvelous 	": new RGB("#EF98AA"),
"Maximum blue 	": new RGB("#47ABCC"),
"Maximum blue green 	": new RGB("#30BFBF"),
"Maximum blue purple 	": new RGB("#ACACE6"),
"Maximum green 	": new RGB("#5E8C31"),
"Maximum green yellow 	": new RGB("#D9E650"),
"Maximum purple 	": new RGB("#733380"),
"Maximum red 	": new RGB("#D92121"),
"Maximum red purple 	": new RGB("#A63A79"),
"Maximum yellow 	": new RGB("#FAFA37"),
"Maximum yellow red 	": new RGB("#F2BA49"),
"May green 	": new RGB("#4C9141"),
"Maya blue 	": new RGB("#73C2FB"),
"Medium aquamarine 	": new RGB("#66DDAA"),
"Medium blue 	": new RGB("#0000CD"),
"Medium candy apple red 	": new RGB("#E2062C"),
"Medium carmine 	": new RGB("#AF4035"),
"Medium champagne 	": new RGB("#F3E5AB"),
"Medium orchid 	": new RGB("#BA55D3"),
"Medium purple 	": new RGB("#9370DB"),
"Medium sea green 	": new RGB("#3CB371"),
"Medium slate blue 	": new RGB("#7B68EE"),
"Medium spring green 	": new RGB("#00FA9A"),
"Medium turquoise 	": new RGB("#48D1CC"),
"Medium violet-red 	": new RGB("#C71585"),
"Mellow apricot 	": new RGB("#F8B878"),
"Mellow yellow 	": new RGB("#F8DE7E"),
"Melon 	": new RGB("#FEBAAD"),
"Metallic gold 	": new RGB("#D3AF37"),
"Metallic Seaweed 	": new RGB("#0A7E8C"),
"Metallic Sunburst 	": new RGB("#9C7C38"),
"Mexican pink 	": new RGB("#E4007C"),
"Middle blue 	": new RGB("#7ED4E6"),
"Middle blue green 	": new RGB("#8DD9CC"),
"Middle blue purple 	": new RGB("#8B72BE"),
"Middle grey 	": new RGB("#8B8680"),
"Middle green 	": new RGB("#4D8C57"),
"Middle green yellow 	": new RGB("#ACBF60"),
"Middle purple 	": new RGB("#D982B5"),
"Middle red 	": new RGB("#E58E73"),
"Middle red purple 	": new RGB("#A55353"),
"Middle yellow 	": new RGB("#FFEB00"),
"Middle yellow red 	": new RGB("#ECB176"),
"Midnight 	": new RGB("#702670"),
"Midnight blue 	": new RGB("#191970"),
"Midnight green (eagle green) 	": new RGB("#004953"),
"Mikado yellow 	": new RGB("#FFC40C"),
"Mimi pink 	": new RGB("#FFDAE9"),
"Mindaro 	": new RGB("#E3F988"),
"Ming 	": new RGB("#36747D"),
"Minion yellow 	": new RGB("#F5E050"),
"Mint 	": new RGB("#3EB489"),
"Mint cream 	": new RGB("#F5FFFA"),
"Mint green 	": new RGB("#98FF98"),
"Misty moss 	": new RGB("#BBB477"),
"Misty rose 	": new RGB("#FFE4E1"),
"Mode beige 	": new RGB("#967117"),
"Morning blue 	": new RGB("#8DA399"),
"Moss green 	": new RGB("#8A9A5B"),
"Mountain Meadow 	": new RGB("#30BA8F"),
"Mountbatten pink 	": new RGB("#997A8D"),
"MSU green 	": new RGB("#18453B"),
"Mulberry 	": new RGB("#C54B8C"),
"Mulberry (Crayola) 	": new RGB("#C8509B"),
"Mustard 	": new RGB("#FFDB58"),
"Myrtle green 	": new RGB("#317873"),
"Mystic 	": new RGB("#D65282"),
"Mystic maroon 	": new RGB("#AD4379"),
"Nadeshiko pink 	": new RGB("#F6ADC6"),
"Naples yellow 	": new RGB("#FADA5E"),
"Navajo white 	": new RGB("#FFDEAD"),
"Navy blue 	": new RGB("#000080"),
"Navy blue (Crayola) 	": new RGB("#1974D2"),
"Neon blue 	": new RGB("#4666FF"),
"Neon Carrot 	": new RGB("#FFA343"),
"Neon green 	": new RGB("#39FF14"),
"Neon fuchsia 	": new RGB("#FE4164"),
"New York pink 	": new RGB("#D7837F"),
"Nickel 	": new RGB("#727472"),
"Non-photo blue 	": new RGB("#A4DDED"),
"Nyanza 	": new RGB("#E9FFDB"),
"Ocean Blue 	": new RGB("#4F42B5"),
"Ocean green 	": new RGB("#48BF91"),
"Ochre 	": new RGB("#CC7722"),
"Old burgundy 	": new RGB("#43302E"),
"Old gold 	": new RGB("#CFB53B"),
"Old lace 	": new RGB("#FDF5E6"),
"Old lavender 	": new RGB("#796878"),
"Old mauve 	": new RGB("#673147"),
"Old rose 	": new RGB("#C08081"),
"Old silver 	": new RGB("#848482"),
"Olive 	": new RGB("#808000"),
"Olive Drab Number 3 	": new RGB("#6B8E23"),
"Olive Drab Number 7 	": new RGB("#3C341F"),
"Olive green 	": new RGB("#B5B35C"),
"Olivine 	": new RGB("#9AB973"),
"Onyx 	": new RGB("#353839"),
"Opal 	": new RGB("#A8C3BC"),
"Opera mauve 	": new RGB("#B784A7"),
"Orange 	": new RGB("#FF7F00"),
"Orange (Crayola) 	": new RGB("#FF7538"),
"Orange (Pantone) 	": new RGB("#FF5800"),
"Orange (web) 	": new RGB("#FFA500"),
"Orange peel 	": new RGB("#FF9F00"),
"Orange-red 	": new RGB("#FF681F"),
"Orange-red (Crayola) 	": new RGB("#FF5349"),
"Orange soda 	": new RGB("#FA5B3D"),
"Orange-yellow 	": new RGB("#F5BD1F"),
"Orange-yellow (Crayola) 	": new RGB("#F8D568"),
"Orchid 	": new RGB("#DA70D6"),
"Orchid pink 	": new RGB("#F2BDCD"),
"Orchid (Crayola) 	": new RGB("#E29CD2"),
"Outer space (Crayola) 	": new RGB("#2D383A"),
"Outrageous Orange 	": new RGB("#FF6E4A"),
"Oxblood 	": new RGB("#800020"),
"Oxford blue 	": new RGB("#002147"),
"OU Crimson red 	": new RGB("#841617"),
"Pacific blue 	": new RGB("#1CA9C9"),
"Pakistan green 	": new RGB("#006600"),
"Palatinate purple 	": new RGB("#682860"),
"Pale aqua 	": new RGB("#BCD4E6"),
"Pale cerulean 	": new RGB("#9BC4E2"),
"Pale Dogwood 	": new RGB("#ED7A9B"),
"Pale pink 	": new RGB("#FADADD"),
"Pale purple (Pantone) 	": new RGB("#FAE6FA"),
"Pale silver 	": new RGB("#C9C0BB"),
"Pale spring bud 	": new RGB("#ECEBBD"),
"Pansy purple 	": new RGB("#78184A"),
"Paolo Veronese green 	": new RGB("#009B7D"),
"Papaya whip 	": new RGB("#FFEFD5"),
"Paradise pink 	": new RGB("#E63E62"),
"Parchment 	": new RGB("#F1E9D2"),
"Paris Green 	": new RGB("#50C878"),
"Pastel pink 	": new RGB("#DEA5A4"),
"Patriarch 	": new RGB("#800080"),
"Payne's grey 	": new RGB("#536878"),
"Peach 	": new RGB("#FFE5B4"),
"Peach (Crayola) 	": new RGB("#FFCBA4"),
"Peach puff 	": new RGB("#FFDAB9"),
"Pear 	": new RGB("#D1E231"),
"Pearly purple 	": new RGB("#B768A2"),
"Periwinkle 	": new RGB("#CCCCFF"),
"Periwinkle (Crayola) 	": new RGB("#C3CDE6"),
"Permanent Geranium Lake 	": new RGB("#E12C2C"),
"Persian blue 	": new RGB("#1C39BB"),
"Persian green 	": new RGB("#00A693"),
"Persian indigo 	": new RGB("#32127A"),
"Persian orange 	": new RGB("#D99058"),
"Persian pink 	": new RGB("#F77FBE"),
"Persian plum 	": new RGB("#701C1C"),
"Persian red 	": new RGB("#CC3333"),
"Persian rose 	": new RGB("#FE28A2"),
"Persimmon 	": new RGB("#EC5800"),
"Pewter Blue 	": new RGB("#8BA8B7"),
"Phlox 	": new RGB("#DF00FF"),
"Phthalo blue 	": new RGB("#000F89"),
"Phthalo green 	": new RGB("#123524"),
"Picotee blue 	": new RGB("#2E2787"),
"Pictorial carmine 	": new RGB("#C30B4E"),
"Piggy pink 	": new RGB("#FDDDE6"),
"Pine green 	": new RGB("#01796F"),
"Pine tree 	": new RGB("#2A2F23"),
"Pink 	": new RGB("#FFC0CB"),
"Pink (Pantone) 	": new RGB("#D74894"),
"Pink flamingo 	": new RGB("#FC74FD"),
"Pink lace 	": new RGB("#FFDDF4"),
"Pink lavender 	": new RGB("#D8B2D1"),
"Pink Sherbet 	": new RGB("#F78FA7"),
"Pistachio 	": new RGB("#93C572"),
"Platinum 	": new RGB("#E5E4E2"),
"Plum 	": new RGB("#8E4585"),
"Plum (web) 	": new RGB("#DDA0DD"),
"Plump Purple 	": new RGB("#5946B2"),
"Polished Pine 	": new RGB("#5DA493"),
"Pomp and Power 	": new RGB("#86608E"),
"Popstar 	": new RGB("#BE4F62"),
"Portland Orange 	": new RGB("#FF5A36"),
"Powder blue 	": new RGB("#B0E0E6"),
"Princeton orange 	": new RGB("#F58025"),
"Process yellow 	": new RGB("#FFEF00"),
"Prune 	": new RGB("#701C1C"),
"Prussian blue 	": new RGB("#003153"),
"Psychedelic purple 	": new RGB("#DF00FF"),
"Puce 	": new RGB("#CC8899"),
"Pullman Brown (UPS Brown) 	": new RGB("#644117"),
"Pumpkin 	": new RGB("#FF7518"),
"Purple 	": new RGB("#6A0DAD"),
"Purple (web) 	": new RGB("#800080"),
"Purple (Munsell) 	": new RGB("#9F00C5"),
"Purple (X11) 	": new RGB("#A020F0"),
"Purple mountain majesty 	": new RGB("#9678B6"),
"Purple navy 	": new RGB("#4E5180"),
"Purple pizzazz 	": new RGB("#FE4EDA"),
"Purple Plum 	": new RGB("#9C51B6"),
"Purpureus 	": new RGB("#9A4EAE"),
"Queen blue 	": new RGB("#436B95"),
"Queen pink 	": new RGB("#E8CCD7"),
"Quick Silver 	": new RGB("#A6A6A6"),
"Quinacridone magenta 	": new RGB("#8E3A59"),
"Radical Red 	": new RGB("#FF355E"),
"Raisin black 	": new RGB("#242124"),
"Rajah 	": new RGB("#FBAB60"),
"Raspberry 	": new RGB("#E30B5D"),
"Raspberry glace 	": new RGB("#915F6D"),
"Raspberry rose 	": new RGB("#B3446C"),
"Raw sienna 	": new RGB("#D68A59"),
"Raw umber 	": new RGB("#826644"),
"Razzle dazzle rose 	": new RGB("#FF33CC"),
"Razzmatazz 	": new RGB("#E3256B"),
"Razzmic Berry 	": new RGB("#8D4E85"),
"Rebecca Purple 	": new RGB("#663399"),
"Red 	": new RGB("#FF0000"),
"Red (Crayola) 	": new RGB("#EE204D"),
"Red (Munsell) 	": new RGB("#F2003C"),
"Red (NCS) 	": new RGB("#C40233"),
"Red (Pantone) 	": new RGB("#ED2939"),
"Red (pigment) 	": new RGB("#ED1C24"),
"Red (RYB) 	": new RGB("#FE2712"),
"Red-orange 	": new RGB("#FF5349"),
"Red-orange (Crayola) 	": new RGB("#FF681F"),
"Red-orange (Color wheel) 	": new RGB("#FF4500"),
"Red-purple 	": new RGB("#E40078"),
"Red Salsa 	": new RGB("#FD3A4A"),
"Red-violet 	": new RGB("#C71585"),
"Red-violet (Crayola) 	": new RGB("#C0448F"),
"Red-violet (Color wheel) 	": new RGB("#922B3E"),
"Redwood 	": new RGB("#A45A52"),
"Resolution blue 	": new RGB("#002387"),
"Rhythm 	": new RGB("#777696"),
"Rich black 	": new RGB("#004040"),
"Rich black (FOGRA29) 	": new RGB("#010B13"),
"Rich black (FOGRA39) 	": new RGB("#010203"),
"Rifle green 	": new RGB("#444C38"),
"Robin egg blue 	": new RGB("#00CCCC"),
"Rocket metallic 	": new RGB("#8A7F80"),
"Rojo Spanish red 	": new RGB("#A91101"),
"Roman silver 	": new RGB("#838996"),
"Rose 	": new RGB("#FF007F"),
"Rose bonbon 	": new RGB("#F9429E"),
"Rose Dust 	": new RGB("#9E5E6F"),
"Rose ebony 	": new RGB("#674846"),
"Rose madder 	": new RGB("#E32636"),
"Rose pink 	": new RGB("#FF66CC"),
"Rose Pompadour 	": new RGB("#ED7A9B"),
"Rose quartz 	": new RGB("#AA98A9"),
"Rose red 	": new RGB("#C21E56"),
"Rose taupe 	": new RGB("#905D5D"),
"Rose vale 	": new RGB("#AB4E52"),
"Rosewood 	": new RGB("#65000B"),
"Rosso corsa 	": new RGB("#D40000"),
"Rosy brown 	": new RGB("#BC8F8F"),
"Royal blue (dark) 	": new RGB("#002366"),
"Royal blue (light) 	": new RGB("#4169E1"),
"Royal purple 	": new RGB("#7851A9"),
"Royal yellow 	": new RGB("#FADA5E"),
"Ruber 	": new RGB("#CE4676"),
"Rubine red 	": new RGB("#D10056"),
"Ruby 	": new RGB("#E0115F"),
"Ruby red 	": new RGB("#9B111E"),
"Rufous 	": new RGB("#A81C07"),
"Russet 	": new RGB("#80461B"),
"Russian green 	": new RGB("#679267"),
"Russian violet 	": new RGB("#32174D"),
"Rust 	": new RGB("#B7410E"),
"Rusty red 	": new RGB("#DA2C43"),
"Sacramento State green 	": new RGB("#043927"),
"Saddle brown 	": new RGB("#8B4513"),
"Safety orange 	": new RGB("#FF7800"),
"Safety orange (blaze orange) 	": new RGB("#FF6700"),
"Safety yellow 	": new RGB("#EED202"),
"Saffron 	": new RGB("#F4C430"),
"Sage 	": new RGB("#BCB88A"),
"St. Patrick's blue 	": new RGB("#23297A"),
"Salmon 	": new RGB("#FA8072"),
"Salmon pink 	": new RGB("#FF91A4"),
"Sand 	": new RGB("#C2B280"),
"Sand dune 	": new RGB("#967117"),
"Sandy brown 	": new RGB("#F4A460"),
"Sap green 	": new RGB("#507D2A"),
"Sapphire 	": new RGB("#0F52BA"),
"Sapphire blue 	": new RGB("#0067A5"),
"Sapphire (Crayola) 	": new RGB("#0067A5"),
"Satin sheen gold 	": new RGB("#CBA135"),
"Scarlet 	": new RGB("#FF2400"),
"Schauss pink 	": new RGB("#FF91AF"),
"School bus yellow 	": new RGB("#FFD800"),
"Screamin' Green 	": new RGB("#66FF66"),
"Sea green 	": new RGB("#2E8B57"),
"Sea green (Crayola) 	": new RGB("#00FFCD"),
"Seal brown 	": new RGB("#59260B"),
"Seashell 	": new RGB("#FFF5EE"),
"Selective yellow 	": new RGB("#FFBA00"),
"Sepia 	": new RGB("#704214"),
"Shadow 	": new RGB("#8A795D"),
"Shadow blue 	": new RGB("#778BA5"),
"Shamrock green 	": new RGB("#009E60"),
"Sheen green 	": new RGB("#8FD400"),
"Shimmering Blush 	": new RGB("#D98695"),
"Shiny Shamrock 	": new RGB("#5FA778"),
"Shocking pink 	": new RGB("#FC0FC0"),
"Shocking pink (Crayola) 	": new RGB("#FF6FFF"),
"Sienna 	": new RGB("#882D17"),
"Silver 	": new RGB("#C0C0C0"),
"Silver (Crayola) 	": new RGB("#C9C0BB"),
"Silver (Metallic) 	": new RGB("#AAA9AD"),
"Silver chalice 	": new RGB("#ACACAC"),
"Silver pink 	": new RGB("#C4AEAD"),
"Silver sand 	": new RGB("#BFC1C2"),
"Sinopia 	": new RGB("#CB410B"),
"Sizzling Red 	": new RGB("#FF3855"),
"Sizzling Sunrise 	": new RGB("#FFDB00"),
"Skobeloff 	": new RGB("#007474"),
"Sky blue 	": new RGB("#87CEEB"),
"Sky blue (Crayola) 	": new RGB("#76D7EA"),
"Sky magenta 	": new RGB("#CF71AF"),
"Slate blue 	": new RGB("#6A5ACD"),
"Slate gray 	": new RGB("#708090"),
"Slimy green 	": new RGB("#299617"),
"Smitten 	": new RGB("#C84186"),
"Smoky black 	": new RGB("#100C08"),
"Snow 	": new RGB("#FFFAFA"),
"Solid pink 	": new RGB("#893843"),
"Sonic silver 	": new RGB("#757575"),
"Space cadet 	": new RGB("#1D2951"),
"Spanish bistre 	": new RGB("#807532"),
"Spanish blue 	": new RGB("#0070B8"),
"Spanish carmine 	": new RGB("#D10047"),
"Spanish gray 	": new RGB("#989898"),
"Spanish green 	": new RGB("#009150"),
"Spanish orange 	": new RGB("#E86100"),
"Spanish pink 	": new RGB("#F7BFBE"),
"Spanish red 	": new RGB("#E60026"),
"Spanish sky blue 	": new RGB("#00FFFF"),
"Spanish violet 	": new RGB("#4C2882"),
"Spanish viridian 	": new RGB("#007F5C"),
"Spring bud 	": new RGB("#A7FC00"),
"Spring Frost 	": new RGB("#87FF2A"),
"Spring green 	": new RGB("#00FF7F"),
"Spring green (Crayola) 	": new RGB("#ECEBBD"),
"Star command blue 	": new RGB("#007BB8"),
"Steel blue 	": new RGB("#4682B4"),
"Steel pink 	": new RGB("#CC33CC"),
"Steel Teal 	": new RGB("#5F8A8B"),
"Stil de grain yellow 	": new RGB("#FADA5E"),
"Straw 	": new RGB("#E4D96F"),
"Sugar Plum 	": new RGB("#914E75"),
"Sunglow 	": new RGB("#FFCC33"),
"Sunray 	": new RGB("#E3AB57"),
"Sunset 	": new RGB("#FAD6A5"),
"Super pink 	": new RGB("#CF6BA9"),
"Sweet Brown 	": new RGB("#A83731"),
"Syracuse Orange 	": new RGB("#D44500"),
"Tan 	": new RGB("#D2B48C"),
"Tan (Crayola) 	": new RGB("#D99A6C"),
"Tangerine 	": new RGB("#F28500"),
"Tango pink 	": new RGB("#E4717A"),
"Tart Orange 	": new RGB("#FB4D46"),
"Taupe 	": new RGB("#483C32"),
"Taupe gray 	": new RGB("#8B8589"),
"Tea green 	": new RGB("#D0F0C0"),
"Tea rose 	": new RGB("#F88379"),
"Tea rose (alt) 	": new RGB("#F4C2C2"),
"Teal 	": new RGB("#008080"),
"Teal blue 	": new RGB("#367588"),
"Telemagenta 	": new RGB("#CF3476"),
"Tenné (tawny) 	": new RGB("#CD5700"),
"Terra cotta 	": new RGB("#E2725B"),
"Thistle 	": new RGB("#D8BFD8"),
"Thulian pink 	": new RGB("#DE6FA1"),
"Tickle Me Pink 	": new RGB("#FC89AC"),
"Tiffany Blue 	": new RGB("#0ABAB5"),
"Timberwolf 	": new RGB("#DBD7D2"),
"Titanium yellow 	": new RGB("#EEE600"),
"Tomato 	": new RGB("#FF6347"),
"Tropical rainforest 	": new RGB("#00755E"),
"True Blue 	": new RGB("#2D68C4"),
"Trypan Blue 	": new RGB("#1C05B3"),
"Tufts blue 	": new RGB("#3E8EDE"),
"Tumbleweed 	": new RGB("#DEAA88"),
"Turquoise 	": new RGB("#40E0D0"),
"Turquoise blue 	": new RGB("#00FFEF"),
"Turquoise green 	": new RGB("#A0D6B4"),
"Turtle green 	": new RGB("#8A9A5B"),
"Tuscan 	": new RGB("#FAD6A5"),
"Tuscan brown 	": new RGB("#6F4E37"),
"Tuscan red 	": new RGB("#7C4848"),
"Tuscan tan 	": new RGB("#A67B5B"),
"Tuscany 	": new RGB("#C09999"),
"Twilight lavender 	": new RGB("#8A496B"),
"Tyrian purple 	": new RGB("#66023C"),
"UA blue 	": new RGB("#0033AA"),
"UA red 	": new RGB("#D9004C"),
"Ultramarine 	": new RGB("#3F00FF"),
"Ultramarine blue 	": new RGB("#4166F5"),
"Ultra pink 	": new RGB("#FF6FFF"),
"Ultra red 	": new RGB("#FC6C85"),
"Umber 	": new RGB("#635147"),
"Unbleached silk 	": new RGB("#FFDDCA"),
"United Nations blue 	": new RGB("#5B92E5"),
"University of Pennsylvania red 	": new RGB("#A50021"),
"Unmellow yellow 	": new RGB("#FFFF66"),
"UP Forest green 	": new RGB("#014421"),
"UP maroon 	": new RGB("#7B1113"),
"Upsdell red 	": new RGB("#AE2029"),
"Uranian blue 	": new RGB("#AFDBF5"),
"USAFA blue 	": new RGB("#004F98"),
"Van Dyke brown 	": new RGB("#664228"),
"Vanilla 	": new RGB("#F3E5AB"),
"Vanilla ice 	": new RGB("#F38FA9"),
"Vegas gold 	": new RGB("#C5B358"),
"Venetian red 	": new RGB("#C80815"),
"Verdigris 	": new RGB("#43B3AE"),
"Vermilion 	": new RGB("#E34234"),
"Vermilion (alt) 	": new RGB("#D9381E"),
"Veronica 	": new RGB("#A020F0"),
"Violet 	": new RGB("#8F00FF"),
"Violet (color wheel) 	": new RGB("#7F00FF"),
"Violet (crayola) 	": new RGB("#963D7F"),
"Violet (RYB) 	": new RGB("#8601AF"),
"Violet (web) 	": new RGB("#EE82EE"),
"Violet-blue 	": new RGB("#324AB2"),
"Violet-blue (Crayola) 	": new RGB("#766EC8"),
"Violet-red 	": new RGB("#F75394"),
"Viridian 	": new RGB("#40826D"),
"Viridian green 	": new RGB("#009698"),
"Vivid burgundy 	": new RGB("#9F1D35"),
"Vivid sky blue 	": new RGB("#00CCFF"),
"Vivid tangerine 	": new RGB("#FFA089"),
"Vivid violet 	": new RGB("#9F00FF"),
"Volt 	": new RGB("#CEFF00"),
"Warm black 	": new RGB("#004242"),
"Wheat 	": new RGB("#F5DEB3"),
"White 	": new RGB("#FFFFFF"),
"Wild blue yonder 	": new RGB("#A2ADD0"),
"Wild orchid 	": new RGB("#D470A2"),
"Wild Strawberry 	": new RGB("#FF43A4"),
"Wild watermelon 	": new RGB("#FC6C85"),
"Windsor tan 	": new RGB("#A75502"),
"Wine 	": new RGB("#722F37"),
"Wine dregs 	": new RGB("#673147"),
"Winter Sky 	": new RGB("#FF007C"),
"Wintergreen Dream 	": new RGB("#56887D"),
"Wisteria 	": new RGB("#C9A0DC"),
"Wood brown 	": new RGB("#C19A6B"),
"Xanadu 	": new RGB("#738678"),
"Xanthic 	": new RGB("#EEED09"),
"Yale Blue 	": new RGB("#00356B"),
"Yellow 	": new RGB("#FFFF00"),
"Yellow (Crayola) 	": new RGB("#FCE883"),
"Yellow (Munsell) 	": new RGB("#EFCC00"),
"Yellow (NCS) 	": new RGB("#FFD300"),
"Yellow (Pantone) 	": new RGB("#FEDF00"),
"Yellow (process) 	": new RGB("#FFEF00"),
"Yellow (RYB) 	": new RGB("#FEFE33"),
"Yellow-green 	": new RGB("#9ACD32"),
"Yellow-green (Crayola) 	": new RGB("#C5E384"),
"Yellow-green (Color Wheel) 	": new RGB("#30B21A"),
"Yellow Orange 	": new RGB("#FFAE42"),
"Yellow Orange (Color Wheel) 	": new RGB("#FF9505"),
"Yellow Sunshine 	": new RGB("#FFF700"),
"YInMn Blue 	": new RGB("#2E5090"),
"Zaffre 	": new RGB("#0014A8"),
"Zomp 	": new RGB("#39A78E"),
}
